---
# handlers file for mysql_server

- name: enable mysql service
  service:
    name: mysql
    enabled: yes

- name: check mysql service status
  shell: systemctl status mysql

- name: check mysql version
  shell: mysql -v
  register: mysql
- debug: var=mysql.stdout_lines

- name: restart mysql
  service:
    name: mysql
    state: restarted